### ISSUE TITLE
Set correct PHP requirements

### ISSUE THREAD

**Issue by Khartir** [qossmic/deptrac-shim#3]
There is a mismatch between the required PHP version of the shim (allowing PHP 7.2) and the PHP version required by deptrac itself (requiring PHP 7.4) in version 0.14. This allows the installation of version 0.14 on older PHP versions but then throws errors on execution. The requirements should be the same.

**Comment by dbrumann** [comment]
Sorry, I missed this issue. I will close this as this should be fixed with the new releases. Feel free to reopen, if you need 0.14 to work correctly and we can figure something out. Sorry for the inconvenience and the late reply.
