### ISSUE TITLE
PHP 8.2 does not match composer.json dependencies

### ISSUE THREAD

**Issue by mcsky** [qossmic/deptrac-shim#9]
Hello, 

I'm trying to upgrade our php version from `8.1` to `8.2`. Unfortunately your package throw me an error when I do a `composer install` because of [php version limited to 8.1](https://github.com/qossmic/deptrac-shim/blob/main/composer.json#L20). 

I will open a PR to increase this version dependency 🙏🏻 

Regards

**Comment by xabbuh** [comment]
Can you clarify what you mean? `^8.1` does not forbid to use the package with PHP 8.2. Which issues did you end up with?

**Comment by gennadigennadigennadi** [comment]
this repository is now abandon.
